using Content.Shared._Stalker_EN.MercBoard;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker_EN.MercBoard;

/// <summary>
/// Main page of the mercenary board with Services and Jobs tabs.
/// Uses a vertical BoxContainer for offer card layout.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STMercBoardMainPage : BoxContainer
{
    /// <summary>Raised when the user presses the Post button. Arg = offer type to post.</summary>
    public event Action<STMercBoardOfferType>? OnPostPressed;

    /// <summary>Raised when the user presses Withdraw on their own offer. Arg = offer ID.</summary>
    public event Action<uint>? OnWithdrawPressed;

    /// <summary>Raised when the user presses Contact on another player's offer. Arg = poster messenger ID.</summary>
    public event Action<string>? OnContactPressed;

    private readonly BoxContainer _cardContainer;
    private STMercBoardUiState? _lastState;
    private bool _showingServices = true;

    public STMercBoardMainPage()
    {
        RobustXamlLoader.Load(this);

        _cardContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 4,
        };
        CardScroll.AddChild(_cardContainer);

        ServicesTabButton.OnPressed += _ => SwitchTab(true);
        JobsTabButton.OnPressed += _ => SwitchTab(false);
        PostButton.OnPressed += _ =>
        {
            var type = _showingServices ? STMercBoardOfferType.Service : STMercBoardOfferType.Job;
            OnPostPressed?.Invoke(type);
        };
    }

    /// <summary>
    /// Updates the page with new state from the server.
    /// </summary>
    public void UpdateState(STMercBoardUiState state)
    {
        _lastState = state;

        ServicesTabButton.Text = Loc.GetString("st-merc-board-tab-services");
        var jobCount = state.Jobs.Count;

        // Show job count badge only for mercs (non-mercs only see their own, less useful)
        if (state.IsMercenary && jobCount > 0)
            JobsTabButton.Text = Loc.GetString("st-merc-board-tab-jobs-count", ("count", jobCount));
        else
            JobsTabButton.Text = Loc.GetString("st-merc-board-tab-jobs");

        RebuildCards();
    }

    private void SwitchTab(bool showServices)
    {
        _showingServices = showServices;
        RebuildCards();
    }

    private void RebuildCards()
    {
        _cardContainer.RemoveAllChildren();

        if (_lastState is null)
            return;

        var offers = _showingServices ? _lastState.Services : _lastState.Jobs;
        var ownerName = _lastState.OwnerCharacterName;
        var isMerc = _lastState.IsMercenary;

        ServicesTabButton.Disabled = _showingServices;
        JobsTabButton.Disabled = !_showingServices;

        if (_showingServices)
        {
            InfoLabel.Text = Loc.GetString("st-merc-board-active-offers", ("count", offers.Count));
            InfoLabel.Visible = true;
        }
        else if (!isMerc)
        {
            // Non-merc jobs tab: show hint text
            InfoLabel.Text = Loc.GetString("st-merc-board-jobs-hint");
            InfoLabel.Visible = true;
        }
        else
        {
            InfoLabel.Text = Loc.GetString("st-merc-board-job-requests", ("count", offers.Count));
            InfoLabel.Visible = true;
        }

        foreach (var offer in offers)
        {
            var isOwn = offer.PosterName == ownerName;
            var card = new STMercBoardOfferCard(offer, isOwn);

            card.OnWithdraw += offerId => OnWithdrawPressed?.Invoke(offerId);
            card.OnContact += posterName => OnContactPressed?.Invoke(posterName);

            _cardContainer.AddChild(card);
        }

        if (_showingServices)
        {
            // Only mercs can post services
            PostButton.Visible = isMerc;
            PostButton.Text = Loc.GetString("st-merc-board-post-service");
            PostButton.Disabled = _lastState.MyServiceCount > 0;
        }
        else
        {
            // Anyone can post job requests
            PostButton.Visible = true;
            PostButton.Text = Loc.GetString("st-merc-board-post-job");
            PostButton.Disabled = _lastState.MyJobCount > 0;
        }
    }
}
