using Content.Shared._Stalker_EN.MercBoard;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.MercBoard;

/// <summary>
/// Post form page for creating a new service offer or job request.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STMercBoardPostPage : BoxContainer
{
    private const int MaxDescriptionLength = 300;

    /// <summary>Raised when the user presses the back button.</summary>
    public event Action? OnBack;

    /// <summary>Raised when the user submits a new offer. Args: offerType, description, price, duration.</summary>
    public event Action<STMercBoardOfferType, string, string, string>? OnSubmit;

    private STMercBoardOfferType _offerType;

    public STMercBoardPostPage()
    {
        RobustXamlLoader.Load(this);

        BackButton.OnPressed += _ => OnBack?.Invoke();

        SubmitButton.OnPressed += _ =>
        {
            var description = Rope.Collapse(DescriptionInput.TextRope).Trim();
            var price = PriceInput.Text.Trim();
            var duration = DurationInput.Text.Trim();

            if (string.IsNullOrEmpty(description) || string.IsNullOrEmpty(price) || string.IsNullOrEmpty(duration))
                return;

            OnSubmit?.Invoke(_offerType, description, price, duration);
            ClearForm();
        };

        DescriptionInput.OnTextChanged += _ => UpdateCharCounter();
        UpdateCharCounter();
    }

    /// <summary>
    /// Configures the form for the given offer type.
    /// </summary>
    public void SetOfferType(STMercBoardOfferType offerType)
    {
        _offerType = offerType;

        TitleLabel.Text = offerType == STMercBoardOfferType.Service
            ? Loc.GetString("st-merc-board-new-service")
            : Loc.GetString("st-merc-board-new-job");

        ClearForm();
    }

    private void ClearForm()
    {
        PriceInput.Text = string.Empty;
        DurationInput.Text = string.Empty;
        DescriptionInput.TextRope = Rope.Leaf.Empty;
        UpdateCharCounter();
    }

    private void UpdateCharCounter()
    {
        var length = (int) Rope.CalcTotalLength(DescriptionInput.TextRope);
        var remaining = MaxDescriptionLength - length;
        CharCounter.Text = Loc.GetString("st-merc-board-char-counter",
            ("remaining", remaining), ("max", MaxDescriptionLength));
    }
}
