using System.Numerics;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Message;
using Content.Client._Stalker_EN.FactionRelations;
using Content.Client._Stalker_EN.UI.Controls;
using Content.Shared._Stalker_EN.News;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.News;

[GenerateTypedNameReferences]
public sealed partial class STNewsUiFragment : BoxContainer, INewsLinkClickHandler
{
    /// <summary>Fired when the journalist publishes an article.</summary>
    public event Action<string, string, int>? OnPublishArticle;

    /// <summary>Fired when the user requests full article content.</summary>
    public event Action<int>? OnRequestArticle;

    /// <summary>Fired when the journalist deletes their own article.</summary>
    public event Action<int>? OnDeleteArticle;

    /// <summary>Fired when the user posts a comment (articleId, content).</summary>
    public event Action<int, string>? OnPostComment;

    /// <summary>Fired when the user navigates back from article detail to list view.</summary>
    public event Action? OnCloseArticle;

    private readonly IClipboardManager _clipboard = IoCManager.Resolve<IClipboardManager>();
    private readonly SpriteSystem _spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

    private static readonly Color CardBackground = Color.FromHex("#1a1a2e");
    private static readonly Color CardBorder = Color.FromHex("#333355");
    private static readonly Color MetaColor = Color.FromHex("#888888");
    private static readonly Color PreviewColor = Color.FromHex("#AAAAAA");
    private static readonly Color NewIndicatorColor = Color.FromHex("#00CC00");

    private const float CardColorBlendFactor = 0.18f;
    private const float CardBorderBlendFactor = 0.30f;

    private static readonly Vector2 FactionIconSize = new(20, 20);
    private static readonly Vector2 ColorSwatchSize = new(24, 24);

    private static readonly (string LocKey, int Color)[] ColorPresets =
    {
        ("st-news-color-military-green", 0x5B7A3A),
        ("st-news-color-rust",           0xB85C38),
        ("st-news-color-amber",          0xC99A2E),
        ("st-news-color-slate",          0x6B7B8D),
        ("st-news-color-dried-blood",    0x8B3A3A),
        ("st-news-color-anomaly-teal",   0x3A8B7A),
        ("st-news-color-psy-purple",     0x6B4A8B),
        ("st-news-color-ash",            0x9B9B8B),
    };

    private int _selectedColor = ColorPresets[0].Color;

    /// <summary>ID of the article currently shown in the detail view, for the copy-link button.</summary>
    private int? _detailArticleId;

    /// <summary>Latest article summaries from server, cached for client-side filtering.</summary>
    private List<STNewsArticleSummary> _lastArticles = new();

    /// <summary>Latest new article IDs from server, cached for client-side filtering.</summary>
    private HashSet<int> _lastNewIds = new();

    /// <summary>Latest deletable article IDs from server, cached for client-side filtering.</summary>
    private HashSet<int> _lastDeletableIds = new();

    /// <summary>Latest new-comment article IDs from server, cached for client-side filtering.</summary>
    private HashSet<int> _lastNewCommentIds = new();

    private readonly List<PanelContainer> _colorPanels = new();

    private static string FormatNewsLink(int id) => $"[NEWS#{id}]";

    public STNewsUiFragment()
    {
        RobustXamlLoader.Load(this);

        HeaderLabel.Text = Loc.GetString("st-news-header");
        WriteButton.Text = Loc.GetString("st-news-write-button");
        NoArticlesLabel.Text = Loc.GetString("st-news-no-articles");
        BackButton.Text = Loc.GetString("st-news-back-button");
        WriterHeaderLabel.Text = Loc.GetString("st-news-writer-header");
        TitleLabel.Text = Loc.GetString("st-news-title-label");
        TitleEdit.PlaceHolder = Loc.GetString("st-news-title-placeholder");
        ContentLabel.Text = Loc.GetString("st-news-content-label");
        ContentEdit.Placeholder = new Rope.Leaf(Loc.GetString("st-news-content-placeholder"));
        EmbedColorLabel.Text = Loc.GetString("st-news-embed-color-label");
        CancelButton.Text = Loc.GetString("st-news-cancel-button");
        PreviewButton.Text = Loc.GetString("st-news-preview-button");
        PublishButton.Text = Loc.GetString("st-news-publish-button");
        PreviewHeaderLabel.Text = Loc.GetString("st-news-preview-header");
        PreviewCancelButton.Text = Loc.GetString("st-news-cancel-button");
        EditButton.Text = Loc.GetString("st-news-edit-button");
        PreviewPublishButton.Text = Loc.GetString("st-news-publish-button");

        DetailCopyLinkButton.Text = Loc.GetString("st-news-copy-link-button");
        DeleteArticleButton.Text = Loc.GetString("st-news-delete-button");
        PostCommentButton.Text = Loc.GetString("st-news-comment-post");
        CommentEdit.Placeholder = new Rope.Leaf(Loc.GetString("st-news-comment-placeholder"));

        WriteButton.OnPressed += _ => ShowWriter();
        BackButton.OnPressed += _ =>
        {
            OnCloseArticle?.Invoke();
            ShowArticleList();
            RebuildArticleList(_lastArticles, _lastNewIds, _lastDeletableIds, _lastNewCommentIds);
        };
        DetailCopyLinkButton.OnPressed += _ =>
        {
            if (_detailArticleId is { } id)
                _clipboard.SetText(FormatNewsLink(id));
        };
        DeleteArticleButton.OnPressed += _ =>
        {
            if (_detailArticleId is { } id)
            {
                OnDeleteArticle?.Invoke(id);
                ShowArticleList();
                RebuildArticleList(_lastArticles, _lastNewIds, _lastDeletableIds, _lastNewCommentIds);
            }
        };
        PostCommentButton.OnPressed += _ =>
        {
            if (_detailArticleId is not { } id)
                return;

            var content = Rope.Collapse(CommentEdit.TextRope).Trim();
            if (string.IsNullOrEmpty(content))
                return;

            OnPostComment?.Invoke(id, content);
            CommentEdit.TextRope = Rope.Leaf.Empty;
            UpdateCommentCounter();
        };
        CancelButton.OnPressed += _ => ShowArticleList();
        PreviewButton.OnPressed += _ => ShowPreview();
        PublishButton.OnPressed += _ => DoPublish();
        PreviewCancelButton.OnPressed += _ => ShowWriter();
        EditButton.OnPressed += _ => ShowWriter();
        PreviewPublishButton.OnPressed += _ => DoPublish();

        TitleEdit.OnTextChanged += _ => UpdateTitleCounter();
        ContentEdit.OnTextChanged += _ => UpdateContentCounter();
        CommentEdit.OnTextChanged += _ => UpdateCommentCounter();

        BuildColorPicker();
        UpdateTitleCounter();
        UpdateContentCounter();
        UpdateCommentCounter();

        SearchBar.OnSearchTextChanged += _ => RebuildArticleList(_lastArticles, _lastNewIds, _lastDeletableIds, _lastNewCommentIds);
    }

    /// <summary>Updates the fragment from the server-provided news UI state.</summary>
    public void UpdateState(STNewsUiState state)
    {
        WriteButton.Visible = state.CanWrite;

        if (state.OpenArticle != null)
        {
            // If already viewing this article, just refresh comments (preserves scroll/input)
            if (ArticleDetailView.Visible && _detailArticleId == state.OpenArticle.Id)
            {
                DeleteArticleButton.Visible = state.CanDeleteOpenArticle;
                RebuildCommentList(state.OpenArticleComments);
            }
            else
            {
                ShowArticleDetail(state);
            }

            // Still update the cached article list for when user goes back
            _lastArticles = state.Articles;
            _lastNewIds = state.NewArticleIds;
            _lastDeletableIds = state.DeletableArticleIds;
            _lastNewCommentIds = state.NewCommentArticleIds;
            return;
        }

        if (state.OpenArticleId != null && state.OpenArticle == null)
            ShowArticleList();

        _lastArticles = state.Articles;
        _lastNewIds = state.NewArticleIds;
        _lastDeletableIds = state.DeletableArticleIds;
        _lastNewCommentIds = state.NewCommentArticleIds;
        RebuildArticleList(state.Articles, state.NewArticleIds, state.DeletableArticleIds, state.NewCommentArticleIds);

        if (!WriterView.Visible && !PreviewView.Visible
            && !ArticleDetailView.Visible)
        {
            ShowArticleList();
        }
    }

    #region View Switching

    private void ShowArticleList()
    {
        ArticleListView.Visible = true;
        ArticleDetailView.Visible = false;
        WriterView.Visible = false;
        PreviewView.Visible = false;
    }

    private void ShowArticleDetail(STNewsUiState state)
    {
        var article = state.OpenArticle!;

        ArticleListView.Visible = false;
        ArticleDetailView.Visible = true;
        WriterView.Visible = false;
        PreviewView.Visible = false;

        _detailArticleId = article.Id;
        DetailTitle.Text = article.Title;
        DetailAuthor.Text = Loc.GetString(
            "st-news-detail-author", ("author", article.Author));
        DetailMeta.Text = Loc.GetString(
            "st-news-detail-meta",
            ("round", article.RoundId),
            ("time", article.PublishTime.ToString(@"hh\:mm\:ss")));
        DetailContent.SetMarkupPermissive(article.Content);

        DeleteArticleButton.Visible = state.CanDeleteOpenArticle;
        RebuildCommentList(state.OpenArticleComments);
        CommentEdit.TextRope = Rope.Leaf.Empty;
        UpdateCommentCounter();
    }

    private void ShowWriter()
    {
        ArticleListView.Visible = false;
        ArticleDetailView.Visible = false;
        WriterView.Visible = true;
        PreviewView.Visible = false;
        UpdateTitleCounter();
        UpdateContentCounter();
    }

    private void ShowPreview()
    {
        ArticleListView.Visible = false;
        ArticleDetailView.Visible = false;
        WriterView.Visible = false;
        PreviewView.Visible = true;

        PreviewTitle.Text = TitleEdit.Text;
        PreviewContent.SetMarkupPermissive(
            Rope.Collapse(ContentEdit.TextRope));
    }

    #endregion

    #region Article List

    private void RebuildArticleList(
        List<STNewsArticleSummary> articles,
        HashSet<int> newArticleIds,
        HashSet<int> deletableIds,
        HashSet<int> newCommentIds)
    {
        ArticleList.RemoveAllChildren();

        var query = SearchBar.SearchText;
        var hasResults = false;

        foreach (var article in articles)
        {
            if (!STSearchFilter.Matches(query, article.Title, article.Author)
                && !STSearchFilter.Matches(query, article.Preview))
            {
                continue;
            }

            var isNew = newArticleIds.Contains(article.Id);
            var canDelete = deletableIds.Contains(article.Id);
            var hasNewComments = newCommentIds.Contains(article.Id);
            ArticleList.AddChild(BuildArticleCard(article, isNew, canDelete, hasNewComments));
            hasResults = true;
        }

        NoArticlesLabel.Visible = !hasResults;
        ArticleScroll.Visible = hasResults;
    }

    private static Color DeriveCardBackground(int embedColor)
    {
        var accent = Color.FromHex($"#{embedColor:X6}");
        return Color.InterpolateBetween(CardBackground, accent, CardColorBlendFactor);
    }

    private static Color DeriveCardBorder(int embedColor)
    {
        var accent = Color.FromHex($"#{embedColor:X6}");
        return Color.InterpolateBetween(CardBackground, accent, CardBorderBlendFactor);
    }

    private Control BuildArticleCard(STNewsArticleSummary article, bool isNew, bool canDelete, bool hasNewComments)
    {
        var card = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = DeriveCardBackground(article.EmbedColor),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
                BorderColor = DeriveCardBorder(article.EmbedColor),
                BorderThickness = new Thickness(0, 0, 0, 1),
            },
            HorizontalExpand = true,
            Margin = new Thickness(4, 2, 4, 2),
        };

        var vbox = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        var titleRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        if (isNew)
        {
            var newLabel = new Label
            {
                Text = Loc.GetString("st-news-new-indicator"),
                FontColorOverride = NewIndicatorColor,
                Margin = new Thickness(0, 0, 6, 0),
            };
            titleRow.AddChild(newLabel);
        }

        var titleLabel = new Label
        {
            Text = article.Title,
            StyleClasses = { "LabelHeading" },
            FontColorOverride = Color.White,
            HorizontalExpand = true,
            ClipText = false,
        };
        titleRow.AddChild(titleLabel);
        vbox.AddChild(titleRow);

        var metaLabel = new Label
        {
            Text = Loc.GetString("st-news-card-meta",
                ("author", article.Author),
                ("round", article.RoundId),
                ("time", article.PublishTime.ToString(@"hh\:mm\:ss"))),
            FontColorOverride = MetaColor,
        };
        vbox.AddChild(metaLabel);

        // Comment count
        if (article.CommentCount > 0)
        {
            var commentText = hasNewComments
                ? Loc.GetString("st-news-card-comments-new", ("count", article.CommentCount))
                : Loc.GetString("st-news-card-comments", ("count", article.CommentCount));

            var commentLabel = new Label
            {
                Text = commentText,
                FontColorOverride = hasNewComments ? NewIndicatorColor : MetaColor,
            };
            vbox.AddChild(commentLabel);
        }

        if (!string.IsNullOrEmpty(article.Preview))
        {
            var previewLabel = new RichTextLabel
            {
                HorizontalExpand = true,
            };
            var previewMsg = new FormattedMessage();
            previewMsg.PushColor(PreviewColor);
            previewMsg.AddText(article.Preview);
            previewMsg.Pop();
            previewLabel.SetMessage(previewMsg);
            vbox.AddChild(previewLabel);
        }

        var buttonRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalAlignment = HAlignment.Right,
            SeparationOverride = 4,
            Margin = new Thickness(0, 4, 0, 0),
        };

        var articleId = article.Id;

        if (canDelete)
        {
            var deleteButton = new Button
            {
                Text = Loc.GetString("st-news-delete-button"),
            };
            deleteButton.OnPressed += _ => OnDeleteArticle?.Invoke(articleId);
            buttonRow.AddChild(deleteButton);
        }

        var copyButton = new Button
        {
            Text = Loc.GetString("st-news-copy-link-button"),
        };
        copyButton.OnPressed += _ =>
            _clipboard.SetText(FormatNewsLink(articleId));
        buttonRow.AddChild(copyButton);

        var readButton = new Button
        {
            Text = Loc.GetString("st-news-read-button"),
        };
        readButton.OnPressed += _ => OnRequestArticle?.Invoke(articleId);
        buttonRow.AddChild(readButton);

        vbox.AddChild(buttonRow);

        card.AddChild(vbox);
        return card;
    }

    #endregion

    #region Comments

    private void RebuildCommentList(List<STNewsComment>? comments)
    {
        CommentList.RemoveAllChildren();

        var count = comments?.Count ?? 0;
        CommentsHeaderLabel.Text = Loc.GetString("st-news-comments-header", ("count", count));

        if (comments == null || comments.Count == 0)
            return;

        foreach (var comment in comments)
        {
            CommentList.AddChild(BuildCommentCard(comment));
        }
    }

    private Control BuildCommentCard(STNewsComment comment)
    {
        var vbox = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 2),
        };

        // Header row: faction icon + author + timestamp
        var header = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
        };

        var factionIcon = new TextureRect
        {
            MinSize = FactionIconSize,
            MaxSize = FactionIconSize,
            Visible = false,
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            Margin = new Thickness(0, 0, 4, 0),
        };

        if (comment.AuthorFaction is not null
            && STFactionPatchIcons.PatchStates.TryGetValue(comment.AuthorFaction, out var patch))
        {
            factionIcon.Texture = _spriteSystem.Frame0(new SpriteSpecifier.Rsi(patch.Rsi, patch.State));
            factionIcon.Visible = true;
        }

        header.AddChild(factionIcon);

        var authorLabel = new Label
        {
            Text = comment.Author,
            StyleClasses = { "LabelKeyText" },
        };
        header.AddChild(authorLabel);

        var timestampLabel = new Label
        {
            Text = Loc.GetString("st-news-comment-timestamp",
                ("round", comment.RoundId),
                ("time", comment.PostedTime.ToString(@"hh\:mm\:ss"))),
            StyleClasses = { "LabelSubText" },
            Margin = new Thickness(8, 0, 0, 0),
        };
        header.AddChild(timestampLabel);

        vbox.AddChild(header);

        var contentLabel = new Label
        {
            Text = comment.Content,
            HorizontalExpand = true,
            ClipText = false,
            Margin = new Thickness(4, 2, 0, 0),
        };
        vbox.AddChild(contentLabel);

        var separator = new HSeparator
        {
            Margin = new Thickness(0, 4, 0, 0),
        };
        vbox.AddChild(separator);

        return vbox;
    }

    private void UpdateCommentCounter()
    {
        var len = (int) Rope.CalcTotalLength(CommentEdit.TextRope);
        var remaining = STNewsConstants.MaxCommentLength - len;
        CommentCounter.Text = $"{remaining}/{STNewsConstants.MaxCommentLength}";
        CommentCounter.FontColorOverride = remaining < 0 ? Color.Red : MetaColor;
        PostCommentButton.Disabled = remaining < 0;
    }

    #endregion

    #region Writer

    private void BuildColorPicker()
    {
        foreach (var (locKey, color) in ColorPresets)
        {
            var panel = new PanelContainer
            {
                MinSize = ColorSwatchSize,
                MaxSize = ColorSwatchSize,
                ToolTip = Loc.GetString(locKey),
                MouseFilter = MouseFilterMode.Stop,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex($"#{color:X6}"),
                    BorderColor = Color.Transparent,
                    BorderThickness = new Thickness(2),
                },
            };

            var colorValue = color;
            var panelRef = panel;
            panel.OnKeyBindDown += args =>
            {
                if (args.Function != Robust.Shared.Input.EngineKeyFunctions.UIClick)
                    return;

                _selectedColor = colorValue;
                UpdateColorSelection(panelRef);
            };

            _colorPanels.Add(panel);
            ColorPicker.AddChild(panel);
        }

        UpdateColorSelection(_colorPanels[0]);
    }

    private void UpdateColorSelection(PanelContainer? selected)
    {
        foreach (var panel in _colorPanels)
        {
            if (panel.PanelOverride is StyleBoxFlat flat)
                flat.BorderColor = panel == selected ? Color.White : Color.Transparent;
        }
    }

    private void DoPublish()
    {
        var title = TitleEdit.Text.Trim();
        var content = Rope.Collapse(ContentEdit.TextRope).Trim();

        if (string.IsNullOrEmpty(title) || string.IsNullOrEmpty(content))
            return;

        OnPublishArticle?.Invoke(title, content, _selectedColor);

        TitleEdit.Text = string.Empty;
        ContentEdit.TextRope = Rope.Leaf.Empty;
        _selectedColor = ColorPresets[0].Color;
        UpdateColorSelection(_colorPanels[0]);

        ShowArticleList();
    }

    private void UpdateTitleCounter()
    {
        var remaining = STNewsConstants.MaxTitleLength - TitleEdit.Text.Length;
        TitleCounter.Text = $"{remaining}/{STNewsConstants.MaxTitleLength}";
        TitleCounter.FontColorOverride = remaining < 0
            ? Color.Red : MetaColor;
    }

    private void UpdateContentCounter()
    {
        var len = (int) Rope.CalcTotalLength(ContentEdit.TextRope);
        var remaining = STNewsConstants.MaxContentLength - len;
        ContentCounter.Text = $"{remaining}/{STNewsConstants.MaxContentLength}";
        ContentCounter.FontColorOverride = remaining < 0
            ? Color.Red : MetaColor;
    }

    #endregion

    #region News Link Handler

    public void HandleNewsLinkClick(int articleId)
    {
        OnRequestArticle?.Invoke(articleId);
    }

    #endregion
}
